### ISSUE TITLE
Authorization using custom claims/policies

### ISSUE THREAD

**Issue by mihaimyh** [blazorbill/WASMAuthenticationMiniSeries#1]
Is there any chance you can show authorization using policies or claims/roles?

**Comment by blazorbill** [comment]
I would be willing to add it but MS updated the way they do authentication. Steve Sanderson gave a demo of roles based using the new authentication on this video (https://www.youtube.com/watch?v=RsPXkgOL2gI&list=PL1rZQsJPBU2St9-Mz1Kaa7rofciyrwWVx&index=3&t=2426s). The demo starts at 29:50. Give it a look and comment back if you still would like me to add it.

**Comment by mihaimyh** [comment]
I know the presentation but unfortunately he didn't showed the implementation of roles or even better policies authorization.

It will be nice if you can add it.

Thanks for videos, really nice content.

**Comment by blazorbill** [comment]
OK...I will try to get it done over the weekend.
